redis:
  client:
    size: 1
    namespace: 'namecheap'
  server:
    size: 5
    namespace: 'namecheap'

exception_notification:
  email_config:
    email_prefix: "[Namecheap App]"
    sender_address: "'Notifier' <notifier@app32547894.mailgun.org>"
    exception_recipients:
      - balaban.petr@gmail.com
